server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:h2:mem:ecommerce-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  jackson:
    default-property-inclusion: NON_NULL
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.boot.context.config: DEBUG