server:
  servlet:
    context-path: /api/v1
  port: 8080
  shutdown: graceful

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
  security:
    user:
      name: admin
      password: 1234
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ecommerce
  datasource:
    url: jdbc:h2:file:./data/ecommerce-db
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    open-in-view: false
  jackson:
    default-property-inclusion: NON_NULL
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.sina.ecommerce: DEBUG